# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true
[cmake]
disabled = true
[package]
disabled = true
[conda]
disabled = true
[python]
symbol = ' '
pyenv_version_name = false
format = 'via [${symbol}(\($virtualenv\) )]($style)'
