" Start pathogen
call pathogen#infect()

" Text Settings
" -------------
set shiftwidth=4 	" auto-ident width when using cindent
set softtabstop=4 	" spaces added when hitting tab
set tabstop=8 		" real tab width
set expandtab

" GUI Settings
" ------------
colorscheme desert

set guioptions=ce 
"              ||
"              |+-- use simple dialogs rather than pop-ups
"              +  use GUI tabs, not console style tabs
if has("gui_gtk2")
	set guifont=DejaVu\ Sans\ Mono\ 9
elseif has("win32") || has("win64")
	set guifont=DejaVu_Sans_Mono:h9:cANSI
endif
