execute pathogen#infect()

" Text Settings
" -------------
set shiftwidth=4 	" auto-ident width when using cindent
set softtabstop=4 	" spaces added when hitting tab
set tabstop=8 		" real tab width
set expandtab

" General Settings
" ----------------
syntax on
filetype plugin indent on  

set autoindent
set backspace=ident,eol,start
set complete-=i
set incsearch
set number
set showcmd
set smarttab

set wildmenu " turn on command line completion wild style
" ignore these list file extensions
set wildignore=*.dll,*.o,*.obj,*.bak,*.exe,*.pyc,*.jpg,*.gif,*.png
            \,*.pdf,*.un~,*.swp
set wildmode=list:longest " turn on wild mode huge list

" GUI Settings
" ------------
"set background=light

if has('gui_running')
    colorscheme solarized
    set cusorline
endif

set guioptions=ce 
"              ||
"              |+-- use simple dialogs rather than pop-ups
"              +  use GUI tabs, not console style tabs
if has("gui_gtk2")
	set guifont=DejaVu\ Sans\ Mono\ 10
elseif has("win32") || has("win64")
	set guifont=DejaVu_Sans_Mono:h9:cANSI
endif

" Plugin Settings
" ---------------
let g:SuperTabDefaultCompletionType = 'context'
autocmd FileType *
    \ if &omnifunc != '' |
    \   call SuperTabChain(&omnifunc, "<c-p>") |
    \ endif
