let g:pathogen_disabled = ['neocomplete', 'neosnippet', 'neosnippet-snippets',
            \'unite', 'vimproc', 'yankstack']
execute pathogen#infect()

" Text Settings
" -------------
set autoindent
set expandtab
set shiftwidth=4 	" auto-ident width when using cindent
set softtabstop=4 	" spaces added when hitting tab
set tabstop=8 		" real tab width

" General Settings
" ----------------
syntax on
filetype plugin indent on  

set autoindent
set backspace=indent,eol,start
set complete-=i
set incsearch
set laststatus=2
set number
set ruler
set shellslash
set showcmd
set smarttab

" turn on command line completion wild style
set wildmenu 
" ignore these list file extensions
set wildignore=*.dll,*.o,*.obj,*.bak,*.exe,*.pyc,*.jpg,*.gif,*.png
            \,*.pdf,*.un~,*.swp
" turn on wild mode huge list
set wildmode=list:longest 

set completeopt=menuone,longest,preview
" Open new windows below the current window
"set splitbelow

" GUI Settings
" ------------
"set background=light

if has('gui_running')
    colorscheme solarized
    set cursorline
    set lines=25 columns=90
endif

set guioptions=ce 
"              ||
"              |+-- use simple dialogs rather than pop-ups
"              +  use GUI tabs, not console style tabs
if has("gui_gtk2")
	set guifont=DejaVu\ Sans\ Mono\ 10
elseif has("win32") || has("win64")
	set guifont=DejaVu_Sans_Mono:h9:cANSI
endif

" Plugin Settings
" ---------------
" Supertab
let g:SuperTabDefaultCompletionType = 'context'
autocmd FileType *
            \ if &omnifunc != '' |
            \   call SuperTabChain(&omnifunc, "<c-p>") |
            \ endif

" CtrlP
let g:ctrlp_root_markers = ['.ctrlp']

" Sneak. Use f instead of s
nmap f <Plug>Sneak_s
nmap F <Plug>Sneak_S
xmap f <Plug>Sneak_s
xmap F <Plug>Sneak_S
omap f <Plug>Sneak_s
omap F <Plug>Sneak_S

" Jedi. Disable selecting first so that tab can be used to select the first.
let g:jedi#popup_select_first = 0
let g:jedi#completions_enabled = 1
