require('settings')
require('keymaps')
require('plugins/packer')
require('plugins/formatter')
require('plugins/nvim-tree')
-- require('plugins/indent-blankline')
-- require('plugins/vista')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/nvim-treesitter')
require('plugins/lualine')
require('plugins/telescope')
require('plugins/tmux-navigation')
require('plugins/neuron')
require('plugins/lightspeed')
