-- Autocommands
-- local autocmd = vim.api.nvim_create_autocmd
-- local augroup = vim.api.nvim_create_augroup
--
-- local misc_aucmds = augroup("misc_aucmds", { clear = true })
--
-- autocmd("TextYankPost", {
-- 	group = misc_aucmds,
-- 	callback = function()
-- 		vim.highlight.on_yank()
-- 	end,
-- })
--
-- autocmd("BufReadPre", {
-- 	group = misc_aucmds,
-- 	callback = function()
-- 		require("config.lsp")
-- 	end,
-- 	once = true,
-- })
